'use client';
import { useMemo, useState } from 'react';
import { Search, X, MousePointer2 } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { resources, resourceGroups } from '@/lib/resources';
import { Choice, ResourceCard } from './knowledge-parts';
export default function ResourceCatalog(){
  const [group,setGroup]=useState('all');const [query,setQuery]=useState('');const [duration,setDuration]=useState('all');const [access,setAccess]=useState('all');
  const filtered=useMemo(()=>resources.filter(r=>(group==='all'||r.group===group)&&(duration==='all'||r.minutes<=Number(duration))&&(access==='all'||access==='no-account'&&['Без аккаунта','Аккаунт для сохранения'].includes(r.access))&&query.toLowerCase().replaceAll('ё','е').trim().split(/\s+/).every(word=>[r.name,r.type,r.task,...r.tags].join(' ').toLowerCase().replaceAll('ё','е').includes(word))),[group,query,duration,access]);
  function reset(){setGroup('all');setQuery('');setDuration('all');setAccess('all')}
  return <><div className="page-title"><div><span className="eyebrow">ПОДБОРКА ДЛЯ УРОКА И ПРАКТИКИ</span><h1>Сервисы и тренажёры</h1><p>Движение на перерыве, учебные мини-игры и короткая практика в программах.</p></div></div><RadioGroup className="category-filters resource-groups" value={group} onValueChange={setGroup} aria-label="Назначение сервиса"><label className={'filter-chip '+(group==='all'?'selected':'')}><RadioGroupItem value="all" className="filter-radio"/><span>Все</span></label>{resourceGroups.map(g=><label key={g.id} className={'filter-chip '+(group===g.id?'selected':'')} style={{'--chip-color':g.color} as React.CSSProperties}><RadioGroupItem value={g.id} className="filter-radio"/><span className="chip-dot" style={{background:g.color}}/><span>{g.name}</span></label>)}</RadioGroup><div className="queue-toolbar resource-toolbar"><div className="search-field"><Search size={20}/><Input aria-label="Поиск сервисов" placeholder="Например: Blockly, перерыв, слои" value={query} onChange={e=>setQuery(e.target.value)} maxLength={200}/>{query?<Button variant="ghost" size="icon" onClick={()=>setQuery('')} aria-label="Очистить поиск сервисов"><X size={18}/></Button>:null}</div><Choice label="Время упражнения" value={duration} onChange={setDuration} items={[{value:'all',label:'Любое время'},{value:'5',label:'До 5 минут'},{value:'15',label:'До 15 минут'}]}/><Choice label="Доступ к сервису" value={access} onChange={setAccess} items={[{value:'all',label:'Любой доступ'},{value:'no-account',label:'Без аккаунта'}]}/></div><div className="resource-intro"><MousePointer2 size={21}/><p>{group==='movement'?'Выберите один короткий ролик, проверьте место и покажите доступный вариант движений. После паузы назовите следующий шаг урока.':group==='creative'?'Творческий перерыв подходит для взаимодействия группы. Для отдыха от экрана запланируйте отдельную паузу с движением.':'Длительность - ориентир для преподавателя. Выберите одну учебную цель и проверьте результат. Домашняя практика добровольная: сначала уточните технику и нагрузку семьи.'}</p></div><div className="catalog-meta"><span role="status" aria-live="polite">Найдено: {filtered.length} из {resources.length}</span>{group!=='all'||query||duration!=='all'||access!=='all'?<Button variant="ghost" size="sm" onClick={reset}>Сбросить фильтры</Button>:null}</div><div className="resource-grid">{filtered.map(r=><ResourceCard id={r.id} key={r.id}/>)}</div>{!filtered.length?<div className="empty-state"><Search size={28}/><h2>Подходящих сервисов пока нет</h2><p>Попробуйте другую категорию, время или поисковое слово.</p><Button variant="outline" onClick={reset}>Все сервисы</Button></div>:null}<p className="muted-note">Условия проверены по официальным страницам 8 октября 2026. Перед уроком откройте выбранный ресурс на учебном компьютере. Рекомендуемые задания составлены для этой базы.</p></>;
}
